kind: ConfigMap
apiVersion: v1
metadata:
  name: ansible-cm
data:
  playbook.yml: |-
    ---
    - name: Deploy Pod to Device Edge
      hosts: rhde-ml
      remote_user: "{{ target_system_user }}"

      tasks:
      - name: Run container
        containers.podman.podman_container:
          name: "{{ container_image_name }}"
          image: "{{ container_image_repo }}/{{ container_image_name }}:{{ container_image_tag }}"
          ports:
            - "8080:8080"
          state: started
      - name: Podman status
        ansible.builtin.command: podman ps
        register: results
      - debug:
          var: results.stdout_lines



  requirements.yml: |
    ---
    collections:
      - name: containers.podman
        source: https://galaxy.ansible.com
