apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: deploy-to-podman-pipeline
  generateName: deploy-to-podman-pipeline-bike-share-
spec:
  params:
  - name: model-name
    value: bike-share-auto-ml
  - name: model-version
    value: "1"
  - name: target-system
    value: "centos-stream9-podman-ssh.sandbox-sbergste.svc.cluster.local"
  - name: target-system-user
    value: "centos"    
  pipelineRef:
    name: deploy-to-podman-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace
  - name: ssh-key-target-system
    secret:
      secretName: ansible-ssh-key
  - configMap:
      name: ansible-cm
    name: ansible-config
